spring:
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 25
          auth: true
          starttls:
            enabled: true
            required: true
    username:
    password:


#https://support.google.com/mail/answer/7104828?hl=en&rd=3&visit_id=637988811351967266-3934073168