spring:
  application:
    name: spring-security-basic
  profiles:
    group:
      in-memory-user:
        - in-memory
        #- security-filter-chain
        - web-security-adapter
      jdbc-user:
        - h2
        - web-security-adapter
      ldap:
        - web-security-adapter

  ldap:
    embedded:
      ldif: classpath:server.ldif
      port: 33389
      base-dn: dc=springland365,dc=com